apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels for all resources
commonLabels:
  app: game-app

resources:
- deployment.yaml

images:
- name: __IMAGE_NAME__
  newName: utibeabasi6/cloudinfra-interview
  newTag: latest